import './globals.css';
import type { Metadata } from 'next';
import GoogleAnalytics from './components/GoogleAnalytics';
import CookieBanner from './components/Cookiebanner';
import useTranslation from 'next-translate/useTranslation';
import { Montserrat, Noto_Sans_TC, Noto_Sans_SC } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const MS = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});
const TC = Noto_Sans_TC({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});
const SC = Noto_Sans_SC({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { lang } = useTranslation();
  let font;
  switch (lang) {
    case 'en-US':
      font = MS.className;
      break;
    case 'zh-TW':
      font = TC.className;
      break;
    case 'zh-CN':
      font = SC.className;
      break;
    default:
      font = MS.className;
  }

  return (
    <html lang={lang} className={font}>
      <GoogleAnalytics GA_MEASUREMENT_ID={process.env.NEXT_PUBLIC_GTM_ID as string} />
      <body className="bg-yellow-100">
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
